condense_wildcard_suffixes   = true
doc_comment_code_block_width = 100
edition                      = "2024"             # Keep in sync with Cargo.toml.
group_imports                = "StdExternalCrate"
imports_granularity          = "Crate"
