[package]
name = "ndg"
version = "0.1.0"
edition = "2021"
description = "ndg - not a docs generator"
license = "MPL"
authors = ["NotAShelf <raf@notashelf.dev>"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
pulldown-cmark = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
tera = "1.20"
syntect = "5.2"
grass = "0.13"
rayon = "1.10"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
fs_extra = "1.3"
num_cpus = "1.16"
lazy_static = "1.5.0"
regex = "1.11.1"

[profile.dev]
opt-level = 1

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
