[package]
name = "ndg"
version = "0.1.0"
edition = "2021"
description = "ndg - not a docs generator"
license = "MPL"
authors = ["NotAShelf <raf@notashelf.dev>"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
pulldown-cmark = "0.13"
pulldown-cmark-to-cmark = "21.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
walkdir = "2.5"
tera = "1.20"
syntect = "5.2"
elasticlunr-rs = "3.0"
grass = "0.13"
rayon = "1.10"
itertools = "0.14"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
fs_extra = "1.3"
num_cpus = "1.16"
lazy_static = "1.5.0"
regex = "1.11.1"
