[package]
name = "ndg"
version = "0.1.0"
edition = "2021"
description = "ndg - not a docs generator"
license = "MPL"
authors = ["NotAShelf <raf@notashelf.dev>"]

[dependencies]
clap = { version = "4.5", default-features = false, features = ["std", "derive", "help", "usage", "suggestions"] }
grass = { version = "0.13", default-features = false, features = [] }
toml = { version = "0.8", default-features = false, features = ["parse"] }
tera = { version = "1.20", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap_complete = "4.5"
clap_mangen = "0.2"
pulldown-cmark = "0.13"
walkdir = "2.5"
syntect = "5.2"
two-face = "0.4"
rayon = "1.10"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
fs_extra = "1.3"
num_cpus = "1.16"
lazy_static = "1.5.0"
regex = "1.11.1"
chrono = "0.4.40"

[profile.dev]
opt-level = 1

[profile.release]
strip = true
opt-level = "s"
lto = "thin"
codegen-units = 1
panic = "abort"

