name: Nix Build

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix:
    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux

    runs-on: ubuntu-latest
    steps:
      - name: "Set up QEMU support"
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: '' # no personalized self-merges tyvm.
          source-url: 'https://install.lix.systems/lix/lix-installer-x86_64-linux'
          logger: pretty
          extra-conf: |
            experimental-features = nix-command flakes fetch-tree
            allow-import-from-derivation = false
            extra-platforms = aarch64-linux


      - name: Checkout
        uses: actions/checkout@v4

      - name: Build packages
        run: nix build -L .#checks.${{ matrix.system }}.default -v

      # For debugging purposes, the default check is standalone so
      # it can be opened or served with zero overhead.
      - name: Upload doc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "ndg-checks-${{ matrix.system }}-default"
          path: result/share/doc/*
          overwrite: true
