name: Nix Build

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix:
    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux

    runs-on: ubuntu-latest
    steps:
      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ''
          source-url: 'https://install.lix.systems/lix/lix-installer-x86_64-linux'

          logger: pretty

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build packages
        run: nix build -L .#checks.${{ matrix.system }}.default -v
